/*
 * This file is generated by jOOQ.
 */

package edu.java.domain.jooq.generation;

import edu.java.domain.jooq.generation.tables.Chat;
import edu.java.domain.jooq.generation.tables.Consists;
import edu.java.domain.jooq.generation.tables.GithubLinks;
import edu.java.domain.jooq.generation.tables.Link;
import edu.java.domain.jooq.generation.tables.StackoverflowLink;
import java.util.Arrays;
import java.util.List;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>DEFAULT_SCHEMA</code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * The table <code>CHAT</code>.
     */
    public final Chat CHAT = Chat.CHAT;

    /**
     * The table <code>CONSISTS</code>.
     */
    public final Consists CONSISTS = Consists.CONSISTS;

    /**
     * The table <code>GITHUB_LINKS</code>.
     */
    public final GithubLinks GITHUB_LINKS = GithubLinks.GITHUB_LINKS;

    /**
     * The table <code>LINK</code>.
     */
    public final Link LINK = Link.LINK;

    /**
     * The table <code>STACKOVERFLOW_LINK</code>.
     */
    public final StackoverflowLink STACKOVERFLOW_LINK = StackoverflowLink.STACKOVERFLOW_LINK;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super("", null);
    }

    @Override
    @NotNull
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    @NotNull
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Chat.CHAT,
            Consists.CONSISTS,
            GithubLinks.GITHUB_LINKS,
            Link.LINK,
            StackoverflowLink.STACKOVERFLOW_LINK
        );
    }
}
