/*
 * This file is generated by jOOQ.
 */

package edu.java.domain.jooq.tables.records;

import edu.java.domain.jooq.tables.StackoverflowLink;
import java.beans.ConstructorProperties;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class StackoverflowLinkRecord extends UpdatableRecordImpl<StackoverflowLinkRecord>
    implements Record3<Long, Long, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Create a detached StackoverflowLinkRecord
     */
    public StackoverflowLinkRecord() {
        super(StackoverflowLink.STACKOVERFLOW_LINK);
    }

    /**
     * Getter for <code>STACKOVERFLOW_LINK.ID</code>.
     */
    @Nullable
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Create a detached, initialised StackoverflowLinkRecord
     */
    @ConstructorProperties({"id", "linkId", "answerCount"})
    public StackoverflowLinkRecord(@Nullable Long id, @Nullable Long linkId, @Nullable Integer answerCount) {
        super(StackoverflowLink.STACKOVERFLOW_LINK);

        setId(id);
        setLinkId(linkId);
        setAnswerCount(answerCount);
        resetChangedOnNotNull();
    }

    /**
     * Getter for <code>STACKOVERFLOW_LINK.LINK_ID</code>.
     */
    @Nullable
    public Long getLinkId() {
        return (Long) get(1);
    }

    /**
     * Create a detached, initialised StackoverflowLinkRecord
     */
    public StackoverflowLinkRecord(edu.java.domain.jooq.tables.pojos.StackoverflowLink value) {
        super(StackoverflowLink.STACKOVERFLOW_LINK);

        if (value != null) {
            setId(value.getId());
            setLinkId(value.getLinkId());
            setAnswerCount(value.getAnswerCount());
            resetChangedOnNotNull();
        }
    }

    /**
     * Getter for <code>STACKOVERFLOW_LINK.ANSWER_COUNT</code>.
     */
    @Nullable
    public Integer getAnswerCount() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row3<Long, Long, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    @NotNull
    public Row3<Long, Long, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * Setter for <code>STACKOVERFLOW_LINK.ID</code>.
     */
    public void setId(@Nullable Long value) {
        set(0, value);
    }

    /**
     * Setter for <code>STACKOVERFLOW_LINK.LINK_ID</code>.
     */
    public void setLinkId(@Nullable Long value) {
        set(1, value);
    }

    /**
     * Setter for <code>STACKOVERFLOW_LINK.ANSWER_COUNT</code>.
     */
    public void setAnswerCount(@Nullable Integer value) {
        set(2, value);
    }

    @Override
    @Nullable
    public Long component1() {
        return getId();
    }

    @Override
    @Nullable
    public Long component2() {
        return getLinkId();
    }

    @Override
    @Nullable
    public Integer component3() {
        return getAnswerCount();
    }

    @Override
    @Nullable
    public Long value1() {
        return getId();
    }

    @Override
    @Nullable
    public Long value2() {
        return getLinkId();
    }

    @Override
    @Nullable
    public Integer value3() {
        return getAnswerCount();
    }

    @Override
    @NotNull
    public StackoverflowLinkRecord value1(@Nullable Long value) {
        setId(value);
        return this;
    }

    @Override
    @NotNull
    public StackoverflowLinkRecord value2(@Nullable Long value) {
        setLinkId(value);
        return this;
    }

    @Override
    @NotNull
    public StackoverflowLinkRecord value3(@Nullable Integer value) {
        setAnswerCount(value);
        return this;
    }

    @Override
    @NotNull
    public StackoverflowLinkRecord values(@Nullable Long value1, @Nullable Long value2, @Nullable Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Field<Long> field1() {
        return StackoverflowLink.STACKOVERFLOW_LINK.ID;
    }

    @Override
    @NotNull
    public Field<Long> field2() {
        return StackoverflowLink.STACKOVERFLOW_LINK.LINK_ID;
    }

    @Override
    @NotNull
    public Field<Integer> field3() {
        return StackoverflowLink.STACKOVERFLOW_LINK.ANSWER_COUNT;
    }
}
