app:
  scheduler:
    enable: true
    interval: 30s
    force-check-delay: 60s
  database-access-type: jdbc
  use-queue: true

kafka:
  producer:
    bootstrap-servers: localhost:9092, localhost:9093
    client-id: scrapper
    ack-mode: all
    delivery-timeout: 60s
    linger-ms: 0
    batch-size: 100_000
    max-in-flight-per-connection: 5
    enable-idempotence: true
  topic:
    name: notification
    partitions: 10
    replicas: 2

spring:
  application:
    name: scrapper
  liquibase:
    enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5433/scrapper
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver

clients:
  github:
    base-url: https://api.github.com
    retry-policy:
      back-off-type: exponential
      max-attempts: 10
      initial-interval: 2000
  stackoverflow:
    base-url: https://api.stackexchange.com/2.3
    retry-policy:
      back-off-type: exponential
      max-attempts: 10
      initial-interval: 2000
  bot:
    base-url: http://localhost:8090
    retry-policy:
      back-off-type: exponential
      max-attempts: 3
      initial-interval: 1000

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
