app:
  scheduler:
    enable: true
    interval: 60s
    force-check-delay: 120s
  database-access-type: jdbc
  use-queue: true

kafka:
  producer:
    bootstrap-servers: localhost:9092, localhost:9093
    client-id: scrapper
    ack-mode: all
    delivery-timeout: 60s
    linger-ms: 0
    batch-size: 100_000
    max-in-flight-per-connection: 5
    enable-idempotence: true
  topic:
    name: notification
    partitions: 10
    replicas: 1


retry:
  back-off-type: constant
  max-attempts: 5
  initial-interval: 2000
  multiplier: 2

spring:
  application:
    name: scrapper
  liquibase:
    enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/scrapper
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver

clients:
  github_base_url: https://api.github.com
  stackoverflow_base_url: https://api.stackexchange.com/2.3
  bot_base_url: https://localhost:8090

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
