app:
  scheduler:
    enable: true
    interval: 60s
    force-check-delay: 120s
  database-access-type: jpa

spring:
  application:
    name: scrapper
  liquibase:
    enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5433/scrapper
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver

clients:
  github:
    base-url: https://api.github.com
    retry-policy:
      back-off-type: constant


  stackoverflow:
    base-url: https://api.github.com



server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
