app:
  telegram-token: 6457945538:AAF7C-GkdB1U0iuSWjZggR8djLGIpL81XRA

spring:
  application:
    name: worker
  jackson:
    time-zone: UTC

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml
