/*
 * This file is generated by jOOQ.
 */

package edu.java.domain.jooq.generation.tables.records;

import edu.java.domain.jooq.generation.tables.pojos.GithubLinks;
import java.beans.ConstructorProperties;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class GithubLinksRecord extends UpdatableRecordImpl<GithubLinksRecord> implements Record3<Long, Long, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Create a detached GithubLinksRecord
     */
    public GithubLinksRecord() {
        super(edu.java.domain.jooq.generation.tables.GithubLinks.GITHUB_LINKS);
    }

    /**
     * Getter for <code>GITHUB_LINKS.ID</code>.
     */
    @Nullable
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Create a detached, initialised GithubLinksRecord
     */
    @ConstructorProperties({"id", "linkId", "countBranches"})
    public GithubLinksRecord(@Nullable Long id, @Nullable Long linkId, @Nullable Integer countBranches) {
        super(edu.java.domain.jooq.generation.tables.GithubLinks.GITHUB_LINKS);

        setId(id);
        setLinkId(linkId);
        setCountBranches(countBranches);
        resetChangedOnNotNull();
    }

    /**
     * Getter for <code>GITHUB_LINKS.LINK_ID</code>.
     */
    @Nullable
    public Long getLinkId() {
        return (Long) get(1);
    }

    /**
     * Create a detached, initialised GithubLinksRecord
     */
    public GithubLinksRecord(GithubLinks value) {
        super(edu.java.domain.jooq.generation.tables.GithubLinks.GITHUB_LINKS);

        if (value != null) {
            setId(value.getId());
            setLinkId(value.getLinkId());
            setCountBranches(value.getCountBranches());
            resetChangedOnNotNull();
        }
    }

    /**
     * Getter for <code>GITHUB_LINKS.COUNT_BRANCHES</code>.
     */
    @Nullable
    public Integer getCountBranches() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row3<Long, Long, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    @NotNull
    public Row3<Long, Long, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * Setter for <code>GITHUB_LINKS.ID</code>.
     */
    public void setId(@Nullable Long value) {
        set(0, value);
    }

    /**
     * Setter for <code>GITHUB_LINKS.LINK_ID</code>.
     */
    public void setLinkId(@Nullable Long value) {
        set(1, value);
    }

    /**
     * Setter for <code>GITHUB_LINKS.COUNT_BRANCHES</code>.
     */
    public void setCountBranches(@Nullable Integer value) {
        set(2, value);
    }

    @Override
    @Nullable
    public Long component1() {
        return getId();
    }

    @Override
    @Nullable
    public Long component2() {
        return getLinkId();
    }

    @Override
    @Nullable
    public Integer component3() {
        return getCountBranches();
    }

    @Override
    @Nullable
    public Long value1() {
        return getId();
    }

    @Override
    @Nullable
    public Long value2() {
        return getLinkId();
    }

    @Override
    @Nullable
    public Integer value3() {
        return getCountBranches();
    }

    @Override
    @NotNull
    public GithubLinksRecord value1(@Nullable Long value) {
        setId(value);
        return this;
    }

    @Override
    @NotNull
    public GithubLinksRecord value2(@Nullable Long value) {
        setLinkId(value);
        return this;
    }

    @Override
    @NotNull
    public GithubLinksRecord value3(@Nullable Integer value) {
        setCountBranches(value);
        return this;
    }

    @Override
    @NotNull
    public GithubLinksRecord values(@Nullable Long value1, @Nullable Long value2, @Nullable Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Field<Long> field1() {
        return edu.java.domain.jooq.generation.tables.GithubLinks.GITHUB_LINKS.ID;
    }

    @Override
    @NotNull
    public Field<Long> field2() {
        return edu.java.domain.jooq.generation.tables.GithubLinks.GITHUB_LINKS.LINK_ID;
    }

    @Override
    @NotNull
    public Field<Integer> field3() {
        return edu.java.domain.jooq.generation.tables.GithubLinks.GITHUB_LINKS.COUNT_BRANCHES;
    }
}
